import Mathlib
import Mathlib.Algebra.LinearRecurrence
import Mathlib.Data.Complex.Basic
import Sequencelib.Meta
namespace Sequence
open Int
open Polynomial
open scoped NumberField
open Finset
open scoped BigOperators

variable (k : ℤ)
variable (p : ℕ) [Fact (Nat.Prime p)]
variable (K : Type*) [Field K] [NumberField K]
variable [IsSplittingField ℚ K (X^2 - C (k : ℚ) * X + 1)] -- K is the splitting field of the characteristic polynomial X^2-kX + 1

--ideal generated by p in the ring of integers 𝓞 K
local notation "I_p" => Ideal.span {(p : 𝓞 K)}

-- quotient of ring of integers of K by I_p.
local notation "O_K_mod_p" => (𝓞 K) ⧸ I_p

lemma hp_zero : (p : O_K_mod_p) = 0 := by
  change Ideal.Quotient.mk I_p (p : 𝓞 K) = 0
  rw [Ideal.Quotient.eq_zero_iff_mem]
  exact Ideal.mem_span_singleton_self _
  
lemma two_unit_lemma  (pod : p ≠ 2) : IsUnit (2 : O_K_mod_p) := by
  have two_coprime : Nat.Coprime 2 p := by
    rw [Nat.coprime_two_left]
    exact (Fact.out : Nat.Prime p).odd_of_ne_two pod
  have two_coprime_ints : IsCoprime (2 : ℤ) (p : ℤ) :=  Nat.isCoprime_iff_coprime.mpr two_coprime
  obtain ⟨u, v, bezouvt⟩ := two_coprime_ints
  have bezouvt_ring_ints : (u : 𝓞 K) * 2 + (v : 𝓞 K) * (p : 𝓞 K) = 1 := by exact_mod_cast bezouvt
  have bezouvt_quot : (u : O_K_mod_p) * 2 + (v : O_K_mod_p) * (p : O_K_mod_p) = 1 := by
    have := congrArg (Ideal.Quotient.mk I_p) bezouvt_ring_ints
    push_cast at this ⊢
    simpa using this
  rw [hp_zero] at bezouvt_quot
  ring_nf at bezouvt_quot
  unfold IsUnit
  exact IsUnit.of_mul_eq_one_right u bezouvt_quot
  -- 4 is a unit in O_K_mod_p .
lemma four_unit_lemma (pod : p ≠ 2): IsUnit (4 : O_K_mod_p) := by
  have two_unit:= two_unit_lemma p K pod
  unfold IsUnit
  unfold IsUnit at two_unit
  obtain ⟨inv, why_inv⟩ := two_unit
  use inv^2
  rw [Units.val_pow_eq_pow_val, why_inv]
  ring
  -- alpha is a root of the characteristic polynomial
lemma old_hroot1_lemma (pod : p ≠ 2) (α β : (O_K_mod_p)ˣ) (hdiff : α ≠ β)
    (κ : O_K_mod_p) (hκ : κ^2 = (k:O_K_mod_p)^2 - 4)
    (hroot1 : 2 * (α : O_K_mod_p) = (k : O_K_mod_p) + κ)
    (hroot2: 2 * (β : O_K_mod_p) = (k : O_K_mod_p) - κ) : (α : O_K_mod_p) ^ 2 - (k : O_K_mod_p) * (α : O_K_mod_p) + 1 = 0 := by
  have multed : (2 * (α : O_K_mod_p))^2 - 2 * (k : O_K_mod_p) * (2 * (α : O_K_mod_p)) + 4 = 0 := by
    simp only [hroot1]
    ring_nf
    linear_combination hκ
  have multiplier : 4 * ((α : O_K_mod_p) ^ 2 - (k : O_K_mod_p) * (α  : O_K_mod_p) + 1) = 0 := by linear_combination multed
  have four_unit := four_unit_lemma p K pod
  exact four_unit.mul_right_eq_zero.mp multiplier

variable [Algebra (ZMod p) ((𝓞 K) ⧸ Ideal.span {(p : 𝓞 K)})]

variable [CharP ((𝓞 K) ⧸ Ideal.span {(p : 𝓞 K)}) p]

noncomputable def f : (O_K_mod_p)ˣ →* (ZMod p)ˣ :=
  Units.map (Algebra.norm (ZMod p))

-- 3. Define your kernel using your map
noncomputable def kappa_p : Subgroup (O_K_mod_p)ˣ :=
  MonoidHom.ker (f p K)

set_option synthInstance.maxHeartbeats 0 in
set_option maxHeartbeats 0 in
lemma alpha_alpha_kappa (pod : p ≠ 2) (α β : (O_K_mod_p)ˣ) (hdiff : α ≠ β)
    (nontriv: NeZero 1)
    (κ : O_K_mod_p) (hκ : κ^2 = (k : O_K_mod_p)^2 - 4)
    (hroot1 : 2 * (α : O_K_mod_p) = (k : O_K_mod_p) + κ)
    (hroot2 : 2 * (β : O_K_mod_p) = (k : O_K_mod_p) - κ)
    (alpha_nonscalar : (α : O_K_mod_p) ∉ Set.range (algebraMap (ZMod p) (𝓞 K ⧸ Ideal.span {(p:𝓞 K)}))) :
    α ∈ kappa_p p K := by
         unfold kappa_p
         show (f p K) α = 1
         unfold f
         have old_hroot1 := old_hroot1_lemma k p K pod α β hdiff κ hκ hroot1 hroot2
         have basis_former : LinearIndependent (ZMod p) ![(1 : O_K_mod_p), (α : O_K_mod_p)] := by
           rw [LinearIndependent.pair_iff]
           intro s t hst
           have snull : s = 0 := by
             by_contra
             apply alpha_nonscalar
             have no_cancel: t ≠ 0 := by
                by_contra cancel
                rw [cancel] at hst
                simp at hst
                rcases hst with left | right
                · contradiction
                · haveI : Nontrivial (𝓞 K ⧸ Ideal.span {(p:𝓞 K)}) := by
                    have hprime : Fact (Nat.Prime p) := inferInstance
                    exact CharP.nontrivial_of_char_ne_one hprime.out.one_lt.ne'
                  exact one_ne_zero right
             use -s/t
             have ha_eq : (t : ZMod p) • (α : O_K_mod_p) = (-s) • (1 : O_K_mod_p) := by
                simp [hst]
                linear_combination hst
             have ha : (α : O_K_mod_p) = algebraMap (ZMod p) O_K_mod_p (-s / t) := by
                have ht_unit : IsUnit t := Ne.isUnit no_cancel
                have hinv : algebraMap (ZMod p) O_K_mod_p t⁻¹ * algebraMap (ZMod p) O_K_mod_p t = 1 := by rw [← map_mul, inv_mul_cancel₀ no_cancel, map_one]
                rw [Algebra.smul_def] at ha_eq
                simp only [Algebra.smul_def] at ha_eq
                simp at ha_eq
                rw [div_eq_mul_inv, map_mul, map_neg]
                linear_combination (algebraMap (ZMod p) O_K_mod_p t⁻¹) * ha_eq - (α : O_K_mod_p) * hinv
             rw[ha]
           have tnull : t = 0 := by
             rw [snull] at hst; simp at hst
             rcases hst with left | right
             · exact left
             · exfalso
               rw [right] at old_hroot1
               simp at old_hroot1
               haveI : Nontrivial (𝓞 K ⧸ Ideal.span {(p:𝓞 K)}) := by
                    have hprime : Fact (Nat.Prime p) := inferInstance
                    exact CharP.nontrivial_of_char_ne_one hprime.out.one_lt.ne'
               exact one_ne_zero old_hroot1
           constructor
           · exact snull
           · exact tnull
         have spans : Submodule.span (ZMod p) ({(1 : O_K_mod_p), (α : O_K_mod_p)} : Set O_K_mod_p) = ⊤ := by
           obtain ⟨w, hw_lift⟩ : ∃ w : 𝓞 K, Ideal.Quotient.mk (Ideal.span {(p : 𝓞 K)}) w = (α : O_K_mod_p) := sorry
           have hw_root : w ^ 2 - (k : 𝓞 K) * w + 1 = 0 := sorry
           have field_up : K = Algebra.adjoin ℚ ({(w : K)} : Set K) := by sorry
           have ring_int : 𝓞 K = Algebra.adjoin ℤ ({w} : Set (𝓞 K)) := by sorry
         sorry
